title: "Base de Datos: Número de Estudiantes por Nivel Educativo en "
description: "Base de datos sobre el n&uacute;mero de estudiantes seg&uacute;n nivel educativo en Am&eacute;rica Latina, con evoluci&oacute;n desde el a&ntilde;o 20"
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/base-de-datos-numero-de-estudiantes-por-nivel-educativo-en-latinoamerica-2000-20"
